version: "3.8"

services:
  react:
    build: ./frontend
    container_name: natalie-dev-react
    command: pnpm run dev
    ports:
      - 3001:3000
    restart: always
    env_file:
      - ./.env.dev
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_EDITOR=${EDITOR}
    volumes:
      - ./frontend/:/srv/app
      - ./frontend/node_modules:/srv/app/node_modules
      - ./frontend/.next:/srv/app/.next
    stop_grace_period: 1s

volumes:
  node_modules:
  media:
  static:
